module.exports.items =  [
    {id:"5cdbdd4f64a2645e9362bb81", name:'LG REFRIG', desc: "LG Refrig", price:670, image:"LGrefrigarator.png", new: "new.gif", logoMarkt: "lglogo.png", info: "The stylish Single Door Refrigerators make ice 40% faster and have better energy-consumption. Not only that - keep your fruits and vegetables fresher longer with the special fruit and vegetable box cover."},

    {id:"5cdbdeab64a2645e9362bb82", name:'DRONE SAMSUNG', desc: "Pocket-drone", price:155, image:"pocketdrone.png", new: "new.gif", logoMarkt: "samsunglogo.png", info: "Samsung, the South Korea-based giant known for making smartphones and other consumer and durable electronics, could be looking to enter the drone market. The company has been active in filing drone patents and a recent drone patent has now been published by the US Patents & Trademark Office."},

    {id:"5cdbdf9764a2645e9362bb83", name:'PHILIPS TV', desc: "PhilipsTV", price:800, image: 'philips-tv.png', logoMarkt: 'Philipslogo.png', info:"Philips TVs had a stellar 2018, boosting the company\u2019s Ambilight line with quality LCDs and one of the best OLED televisions we\u2019ve ever seen, the Philips OLED+ 903. Facing stiff competition this year from the Panasonic GZ2000 and LG\u2019s barmy rollable TV."},

    {id:"5cdbe03564a2645e9362bb84", name:'IPHONE XR', desc: "Iphone-XR", price:800, image: 'iPhoneXR.png', logoMarkt: 'applelogo.png', info:"iPhone XR helps us reach even more people with the latest iPhone innovations. It is packed with the newest technologies including a 6.1-inch Liquid Retina display that goes edge to edge, the latest TrueDepth camera with faster Face ID authentication, new 7-nanometer A12 Bionic chip with second generation Neural Engine and a 12-megapixel camera that takes advanced Portrait mode and Portrait Lighting photos,\u201d said Philip Schiller, Apple\u2019s senior vice president of Worldwide Marketing."},

    {id:"5cdbe0e964a2645e9362bb85", name:'PIONEER HEADPHONE', desc: "DJ Headphone", price:250, image:'pioneerheadphone.png', logoMarkt: 'pioneerlogo.png', info: "You can get away with using regular cheap headphones, but it does add a sense of strain to your mixes. A nice pair of DJ headphones allow you to hear exactly what your mixing into and it just looks very professional!"},

    {id:"5cdbe22864a2645e9362bb86", name:'DELL LAPTOP', desc: "Dell-Laptop", price:500, image: 'DellLaptopPNGImage.png', new: "new.gif", logoMarkt: 'delllogo.png',info: "Dell is an American multinational computer technology company based in Round Rock, Texas, United States, that develops, sells, repairs, and supports computers and related products and services. Named after its founder, Michael Dell, the company is one of the largest technological corporations in the world, employing more than 145,000 people in the U.S. and around the world (Annual report 2018)."}, 

    {id:"5cdbe39464a2645e9362bb87", name:'ASUS MONITOR', desc: "Zoll-Monitor-Metal", price:289, image: 'asus.png', logoMarkt: 'asuslogo.png', info: "Dieser 15 Zoll Monitor mit 4:3 Seitenverhätlnis bietet eine erstklassige Bildqualität mit naturgetreuen Farben. Der Monitor besticht mit einem klaren und gestochen scharfen LED-IPS Panel mit exzellentem 178° Betrachtungswinkel. Der 15VGM hat ein stabiles Metallgehäuse und verfügt über je einen HDMI, VGA, BNC und RCA-Cinch Anschluss. Weiterhin ist der Monitor hervorragend zum Einbau oder zur Wand- und Tischmontage geeignet."},

    {id:"5cdbe48364a2645e9362bb88", name:'REEBOK SHOES', desc:"Reebok-running-shoe", price:190, image: 'Reebokshoe.png', logoMarkt: 'reeboklogo.png', info: "Dieser Athleisure-Schuh ist alles, was du für einen ernsthaft coolen Look brauchst. Dank unserer adaptiven Heritage-Dämpfung bist du den ganzen Tag lang bequem unterwegs, während die überdimensionierte Außensohle der DMX-Serie garantiert alle Blicke auf sich ziehen wird."},

    {id:"5cdbe50a64a2645e9362bb89",  name:'AMAZON CAMERA', desc:"cloudcam", price:750, image: 'cloudcam.png', logoMarkt: 'amazon_PNG13.png', info: "new home security camera, Cloud Cam, with a companion Amazon Key app that works with smart locks to let Amazon Prime members give house cleaners, dog walkers, package delivery companies and other service providers access to their homes."},

    {id:"5cdbe5b564a2645e9362bb8a", name:'MAC PRO', desc:"Apple-MacBook-Pro", price:7649, image: 'macpro.png', logoMarkt: 'applelogo.png', info: "Das MacBook Pro ist aus einem einzigen Aluminumblock gefertigt - eine technische Meisterleistung, bei der viele Bauteile durch ein einziges ersetzt werden. Das Ganze nennt sich Unibody. Gleich beim ersten Mal, wenn du ein MacBook Pro in der Hand hast, wirst du den Unterschied spüren. Das Gehäuse ist dünner und leichter als andere Notebooks. Es sieht elegant aus. Und es fühlt sich stabil und robust an: perfekt für die Aktentasche, den Rucksack und natürlich auch für draußen."},

    {id:"5cdbe62564a2645e9362bb8b", name:'SAMSUNG', desc:"HW-K20-Multimedia", price:250, image: 'speker.png', logoMarkt: 'samsunglogo.png', info: "The Multimedia Speaker has a convenient USB port, so listening to all your favourite tracks is as simple as plugging in your USB drive. From MP3s to WMAs, it can playback a variety of music files to deliver great sound."},

    {id:"5cdbe68464a2645e9362bb8c", name:'APPLE WATCH', desc:"apple-watch 3", price:250, image: 'smartwatchApple.png', logoMarkt: 'applelogo.png', info: "Monitor your health. Track your workouts. Get the motivation you need to achieve your fitness goals. And stay connected to the people and information you care about. With Apple Watch Series 3, you can do it all right from your wrist"},
    
    {id:"5cdbe71764a2645e9362bb8d", name:'NIKE', desc:"Nike-Air-VaporMax-Flyknit-3", price:210, image: 'shose.png', logoMarkt: 'nikelogo.png',new: "new.gif", info: "Der Nike Air VaporMax Flyknit 3 mit dynamischen, zweifarbigen Linien einer atmungsaktiven, dehnbaren Flyknit-Konstruktion präsentiert einzigartigen Street-Style. Revolutionäre VaporMax Air-Technologie hält dich mit Polsterung von Zeh bis Ferse immer auf flinkem Fuß"},

    {id:"5cdbe78d64a2645e9362bb8e", name:'SAMSUNG SMART', desc:"Galaxy-watch", price:260, image: 'samsung-smart.png', logoMarkt: 'samsunglogo.png', info: "Live a stronger, smarter life with the watch that lets you stay connected without reaching for your phone.With sleep cycle & calorie tracking, guided breathing exercises, individual workout detection and GPS capabilities for long runs, you have everything you need at your wrist."},

    {id:"5cdbe7fc64a2645e9362bb8f", name:'PUMA', desc:"Puma-blue-long-sleeve-t-shirt", price:15, image: 'puma.png', logoMarkt: 'pumalogo.png', info: "Show off a clean look to elevate your street game with the 2 blue long sleeve t-shirt from PUMA and blue Scale. Cut from a heavy-weight cotton for a comfortable fit, this blue design features a PUMA logo graphic printed on the chest, a blue Scale logo graphic printed on the back."},

    {id:"5cdbe9d664a2645e9362bb90" , name:'LG', desc:"LG-G7-ThinQ-64GB", price:350, image: 'shose.png', logoMarkt: 'lglogo.png', info: "The LG G7 ThinQ utilizes a metal chassis with a glass backing, and is IP68-rated for water and dust-resistance.The G7 utilizes the Qualcomm Snapdragon 845 system-on-chip with 4 GB of RAM."},

    {id:"5cdbea5664a2645e9362bb91",name:'IPHONE XS', desc:"Iphone-Xs", price:1099, image: 'iphonexs.png', logoMarkt: 'applelogo.png', info: "Exceptional materials. The most durable glass ever in a smartphone. A beautiful new gold finish, achieved with an atomic-level process. Precision-machined, surgical-grade stainless steel bands. And a new level of water and dust resistance"},

    {id:"5cdbeb1564a2645e9362bb92", name:'HTC', desc:"Htc-U12", price:400,  image: 'htc.png', logoMarkt: 'images/htclogo.png', info: "Specs and camera. Under the hood the HTC U12 Plus is powered by a Qualcomm Snapdragon 845 processor along with 6GB of RAM and either 64GB or 128GB of storage. ... There are two cameras on the rear, with one 12-megapixel lens with an aperture of f/1.75, and one 16-megapixel telephoto lens with an aperture of f/2.6"},

    {id:"5cdbebd864a2645e9362bb93", name:'HAUAWIE SMART', desc:"Hauawi-Smart-S4", price:227, image: 'huawei.png', logoMarkt: 'huawielogo.png', info: " Strong Featuring a double crown AMOLED screen and lightweight design this watch is classy and sleek. Pair that with a ceramic bezel design and stainless steel shell you are ready to explore."},

    {id:"5cdbec6d64a2645e9362bb94", name:'ADIDAS', desc:"adidas-mens-ultimate-long-sleeve-t-shir",price:28, image: 'adidas.png', logoMarkt: 'adidaslogo.png', info: "Built for multisport training, this mens long sleeve t-shirt is designed to help you power through your toughest workouts. Made of lightweight quick-drying fabric, the shirt has a soft cotton feel that adds comfort to your performance."},

    {id:"5cdbdbef64a2645e9362bb80", name:'SAMSUNG S10', desc:"Samsung S10 128GB-8GB/RAM", price:899, image: 'samsungs10.png', logoMarkt: 'samsunglogo.png',new: "new.gif", info: "The Galaxy S10 is a fitting 10th anniversary phone for Samsung and its storied S series. It delivers on change with a novel-looking Infinity-O screen so large it displaces the front camera, and a triple-lens rear camera that takes ultra-wide photos. Its in-screen fingerprint sensor tech should serve you well, while its Wireless PowerShare could serve your friends well. That\u2019s a lot of change \u2013 just know that it comes at a high price and the Galaxy S10e and S10 Plus flank it from both sides of the coin as better options."}
]
